package com.reranko.cloud_storage.mini_drive.user.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity // This class represents a table in the database
@Table(name = "users") // The table is named "users"
public class User {

    @Id // Primary key of the table
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true) // Email must be unique and cannot be null
    private String email;

    @Column(nullable = false) // Password cannot be null
    private String password;

    @Column(nullable = false) // Creation timestamp cannot be null
    private LocalDateTime createdAt;
    
    // Constructor to create a new User with email, password, and creation time
    public User() { // Default constructor needed by JPA
    }

    public Long getId() { // Getter for id, JPA fills the id field automatically, so no setter is needed
        return id;
    }

    /* The ID is generated by the database and represents immutable idenity, so exposing a setter risks corrupting data integrity.
     * Therefore, no setter for ID is provided.
     */

    public String getEmail() { // Getter for email
        return email;
    }

    public void setEmail(String email) { // Setter for email
        this.email = email;
    }

    public String getPassword() { // Getter for password
        return password;
    }

    public void setPassword(String password) { // Setter for password
        this.password = password;
    }

    public LocalDateTime getCreatedAt() { // Getter for createdAt
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) { // Setter for createdAt
        this.createdAt = createdAt;
    }
}