spring:
  application:
    name: mini-drive
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

jwt:
  secret: 9f8e7d6c5b4a3a2f1e0d9c8b7a6f5e4d3c2b1a0f
  expiration: 900000
